service: facecomparison-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: java17
  region: us-east-1
  apiName: facecomparison-api-${opt:stage, 'dev'}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:*
      Resource:
        - "*"

  environment:
    stage: ${opt:stage, 'dev'}
    region: ${aws:region}
    service: facecomparison-api

plugins:
  - serverless-manifest-plugin

custom:
  stage: ${opt:stage, 'dev'}
  product: youtube

package:
  artifact: target/facecomparison-0.0.1-SNAPSHOT.jar

functions:
  app:
    handler: io.github.lucasiferreira.facecomparison.config.StreamLambdaHandler
    name: facecomparison-api-${opt:stage, 'dev'}
    events:
      - http:
          cors: true
          path: /facecomparison/{proxy+}
          method: any
