service: image-comparison-tool

provider:
  name: aws
  runtime: java17
  region: us-east-1
  apiName: ${self:service}-${self:custom.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:*
      Resource:
        - "*"
  environment:
    stage: ${self:custom.stage}
    region: ${aws:region}
    service: ${self:service}

plugins:
  - serverless-manifest-plugin

custom:
  stage: ${sls:stage}
  product: youtube

package:
  artifact: target/facecomparison-0.0.1-SNAPSHOT.jar

functions:
  app:
    handler: io.github.lucasiferreira.facecomparison.config.StreamLambdaHandler
    name: ${self:service}-${self:custom.stage}
    events:
      - http:
          path: /facecomparison/{proxy+}
          method: any
          cors:
            origin: 'https://lucas-iferreira.github.io'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
